### ISSUE TITLE
  File "labelReader.py", line 4, in <module>     from utils.darknet_classify_image import * ImportError: No module named utils.darknet_classify_image

### ISSUE THREAD

**Issue by NightFury10497** [ecthros/labelReader#5]
![image](https://user-images.githubusercontent.com/30961652/43315033-61173d9e-91b2-11e8-90ac-9ad4f9f6dc03.png)

Traceback (most recent call last):
  File "labelReader.py", line 4, in <module>
    from utils.darknet_classify_image import *
ImportError: No module named utils.darknet_classify_image

**Comment by ecthros** [comment]
Can you show me the contents of the utils folder? The file should be right there.

**Comment by NightFury10497** [comment]
![image](https://user-images.githubusercontent.com/30961652/43341403-00b886c4-91fd-11e8-8947-8fdc7d4a4207.png)

Can you tell me to steps to config it ?
I am using Linux  and I have gone through  your steps given 
Pleas guide a bit more.

**Comment by getcontrol** [comment]
Same problem as well . Contents of my utils/ 
![Screenshot 2019-11-10 14 25 07](https://user-images.githubusercontent.com/9941190/68551876-ebef7180-03c5-11ea-9259-0a6e17eb051f.png)
