### ISSUE TITLE
INITIALIZATION IS FAILING in both Keras and Darknet  at the time of their classification.

### ISSUE THREAD

**Issue by NightFury10497** [ecthros/labelReader#6]
![image](https://user-images.githubusercontent.com/30961652/43341621-af42f3aa-91fd-11e8-920d-b3230ee1341e.png)
![image](https://user-images.githubusercontent.com/30961652/43341677-dd25638e-91fd-11e8-85c9-e2f2103ef684.png)
 By running both Darknet  n Keras both give a INIT classifier failed , exiting now.

**Comment by ecthros** [comment]
It looks like you may need to recompile the corresponding binaries - they were compiled for my system, which will be different than yours.

On the other hand, I'd suggest using the docker image. It should be much easier to use as the dependencies are automatically installed.

**Comment by NightFury10497** [comment]
But when i  make the docker image , and further use it 
I have to clone the labelReader again  and then it gives me another  IMPORT ERROR for utlis 
Please Guide on the same.

**Comment by ecthros** [comment]
You shouldn't be getting an import error if you've correctly downloaded the whole repo. Here are the steps I've just taken to confirm everything is working:

```
docker pull continuumio/miniconda3
docker run continuumio/miniconda3 /bin/bash
apt update
git clone https://github.com/ecthros/labelReader
cd labelReader
./install.sh
python labelReader.py -k -t
```
Can you confirm you are doing these same steps?

**Comment by NightFury10497** [comment]
Sure, I will  try it and get  back to you on the same.
Will run the commands on Ubuntu 16.04 , if any changes let me know.

**Comment by NightFury10497** [comment]
![image](https://user-images.githubusercontent.com/30961652/43386521-7781fb72-9401-11e8-9f53-e047f605eced.png)
Tried configuring all of them , giving the same error

It should be python 2 or 3?

**Comment by ecthros** [comment]
It should be python3. 

It looks like your config is failing with the error:
error: command 'gcc' failed with exit status 1.

Do you have gcc installed? Make sure to run install.sh, it should install gcc for you.

**Comment by NightFury10497** [comment]
Thanks , the error was with GCC only , but Keras is still failing in Initializing  the Classifier.
Can you tell  from where to pick the images , the specific folder  or the location  from where we can train our own data

**Comment by NightFury10497** [comment]
![image](https://user-images.githubusercontent.com/30961652/43470030-35a7fb3e-9505-11e8-8068-3dcdb9b1facd.png)
Keras is still failing in Initializing the Classifier.

**Comment by ecthros** [comment]
I've added some samples in the samples/ directory. Note that my model is trained on similar samples. 
If you want to train your own model, I'd suggest looking at the README - it has steps on how to train for Darknet. 
For the Keras classifier, I'm guessing it's missing a dependency. Please try to run install.sh to completion. If it's finishing, head over to the keras-yolo3 directory and try running `python convert.py` and `python yolo.py`. See if those have errors.

**Comment by NightFury10497** [comment]
Where is the samples directory ? and how should i access them ?
ok i will try keras one and get back to  you

**Comment by ecthros** [comment]
Oops, forgot to push - it should  be in the root of the repo now

**Comment by NightFury10497** [comment]
Thanks, I will clone it again and  compile it and get back to you  on the same.

**Comment by NightFury10497** [comment]
![image](https://user-images.githubusercontent.com/30961652/43477436-cd2264e6-9518-11e8-977d-5101f5fc0613.png)
Didn't workout

**Comment by ecthros** [comment]
Looks like they've updated keras-yolo3. While I'm working on a permanent fix, do the following to revert to the earlier commit:

```
cd keras-yolo3
git checkout da7d756b0e47b979e701f0131ba7074ea138add8
```

Those steps should fix the error.
As a side note, you don't need both keras and darknet to work at the same time, only one.

**Comment by NightFury10497** [comment]
cd keras-yolo3 git checkout da7d756b0e47b979e701f0131ba7074ea138add8 ??

**Comment by ecthros** [comment]
That will check out the older version. 

Alternatively, you don't have to run those commands - I've added the more permanent fix so you can just do a `git pull` again.

**Comment by NightFury10497** [comment]
On IT!

**Comment by ecthros** [comment]
Awesome, let me know when I can close this issue.

**Comment by NightFury10497** [comment]
If i have to train the darknet , i gotta make my own dataset right ?
Working with Keras as well , Thank YOU.

**Comment by ecthros** [comment]
Awesome. And yes, you'll need to train your own dataset, but you can follow the steps in the README to do so.

**Comment by NightFury10497** [comment]
Hey!
![image](https://user-images.githubusercontent.com/30961652/43542058-9f2d9796-95e9-11e8-9847-cee575c47027.png)
IT came with this issue now

**Comment by ecthros** [comment]
You can try changing the language for tesseract - it looks like it's using an incorrect language.
