### ISSUE TITLE
nameplate_confidence = nameplate_info[1] IndexError: list index out of range

### ISSUE THREAD

**Issue by 008karan** [ecthros/labelReader#7]
I am able to sample images but when I test with other give above error.

**Comment by ecthros** [comment]
I can take a look soon, could you tell me what options you ran the program with?

**Comment by 008karan** [comment]
Used python labelReader -d - t

**Comment by ecthros** [comment]
Hi - I can't reproduce this. Could you give me the picture you're using?

Also please let me know if you're using docker and any system information.

**Comment by 008karan** [comment]
I am using Docker. Followed the given method for all dependencies. 
 try this image:
[http://www.diabetescare.net/CMS/DOCS/userfiles/image/Images%20-%20Logos/Photos_com%20Images/Nutrition%20Label.jpg]

**Comment by ecthros** [comment]
I'll need to take a closer look, but I believe the issue is that I'm only supporting PNG files. I'll work on a longer term fix in the meantime.

**Comment by 008karan** [comment]
Are you able to reproduce it?. Its working with . jpg files as sample images are jpg only and test image I gave is also jpg.

**Comment by ecthros** [comment]
Try pulling and try again. I think the issue may have been because your filename contained the word "label." Since that happens to also be the name of the object detected, my code automatically flagged it as a successfully found object, but it should not have been.

Let me know if this fixes the problem.

**Comment by 008karan** [comment]
I have tried with many images. So its not the case of  image name.

**Comment by 008karan** [comment]
which annotation format should I choose yolo or pascal voc?

**Comment by ecthros** [comment]
Yolo Format - both the darknet and keras implementations I have for Object detection use YOLO.
